# Generated by Django 3.2.9 on 2021-11-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('name', models.IntegerField(choices=[(921, 'win1'), (3150, 'win1'), (3144, 'win1'), (922, 'draw'), (3152, 'draw'), (923, 'win2'), (3151, 'win2'), (3145, 'win2'), (924, 'win1draw'), (1571, 'notDraw'), (925, 'win2draw'), (927, 'fora1'), (937, 'fora1'), (1845, 'fora1'), (928, 'fora2'), (938, 'fora2'), (1846, 'fora2'), (930, 'totalOver'), (940, 'totalOver'), (1848, 'totalOver'), (931, 'totalUnder'), (941, 'totalUnder'), (1849, 'totalUnder')], verbose_name='factor_name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='value')),
                ('param', models.CharField(blank=True, max_length=255, null=True, verbose_name='param')),
                ('score', models.CharField(blank=True, max_length=255, null=True, verbose_name='score')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='comment')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
    ]
