# Generated by Django 3.2.9 on 2021-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklog',
            name='name',
        ),
        migrations.AddField(
            model_name='blocklog',
            name='factor',
            field=models.IntegerField(choices=[(921, 'win1'), (3150, 'win1'), (3144, 'win1'), (922, 'draw'), (3152, 'draw'), (923, 'win2'), (3151, 'win2'), (3145, 'win2'), (924, 'win1draw'), (1571, 'notDraw'), (925, 'win2draw'), (927, 'fora1'), (937, 'fora1'), (1845, 'fora1'), (928, 'fora2'), (938, 'fora2'), (1846, 'fora2'), (930, 'totalOver'), (940, 'totalOver'), (1848, 'totalOver'), (931, 'totalUnder'), (941, 'totalUnder'), (1849, 'totalUnder')], default=-1, verbose_name='factor'),
        ),
        migrations.AlterField(
            model_name='blocklog',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
    ]
