# Generated by Django 3.2.9 on 2021-11-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211129_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='event_id',
            field=models.IntegerField(),
        ),
    ]
