# Generated by Django 3.2.9 on 2021-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_blocklog_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='event_id',
            field=models.IntegerField(verbose_name='event_id'),
        ),
    ]
