# Generated by Django 3.2.9 on 2021-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_blocklog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklog',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
    ]
